### ISSUE TITLE
First meetup 20/05/2017

### ISSUE THREAD

**Issue by dnson** [tanduong/hcm-frontend-meetup#1]

**Comment by Thoi-Duong** [comment]
time: 9h, 20/05/2017
location: cty 1Pac, tầng 6, 244 Cống Quỳnh, Phạm Ngũ Lão, Quận 1, Hồ Chí Minh
sdt: Thời 0942972713

**Comment by dnson** [comment]
Server-Side Rendering with React

**Comment by tanduong** [comment]
I will talk about Redux. For ref: http://redux.js.org/docs

**Comment by Thoi-Duong** [comment]
I will talk about geting started with React Native, Ref: https://facebook.github.io/react-native/

**Comment by pnminh92** [comment]
I will listen to what you guys talk :octocat:

**Comment by huuthonguyen76** [comment]
✌️

**Comment by tanduong** [comment]
Here is the materials for graphql talk:

[Zero to GraphQL in 30 Minutes – Steven Luscher](https://www.youtube.com/watch?v=UBGzsb2UkeY)

[zero-to-graphql (example of graphql in 5 popular  PL/ frameworks](https://github.com/steveluscher/zero-to-graphql)

[Relay docs](https://facebook.github.io/relay/)

[Graphql doc](http://graphql.org/learn/)

[Relay todo mvc example](https://github.com/relayjs/relay-examples)
